spring.application.name=sep490-g94-sp26-be

# Server
server.port=8080
spring.docker.compose.enabled=false
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/wedding_services
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=wedding

spring.servlet.multipart.max-file-size=40MB
spring.servlet.multipart.max-request-size=40MB

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# MinIO Configuration
minio.endpoint=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin123
minio.bucket=wedding-assets

# PayOS Configuration
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
payos.base-url=${PAYOS_BASE_URL:https://api-merchant.payos.vn}
payos.create-payment-path=${PAYOS_CREATE_PAYMENT_PATH:/v2/payment-requests}
payos.return-url=${PAYOS_RETURN_URL:http://localhost:3000/payment/success}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:3000/payment/cancel}

# Mailtrap Configuration
mailtrap.token=${MAILTRAP_TOKEN}
mailtrap.email=${MAILTRAP_EMAIL}
